#+TITLE: Basic Css and The Diffrent between Class and ID.
#+Author: Mohammed K Alnahdi
#+Email: mohammed.alnahdi1991@gmail.com
#+Date: <2022-03-13 Sun>

* Introduction
In this tutorial we will explain the basic Css and the diffrent between Class and ID.

* Usage
Basic in css it is include in four ways.

** Css control every tags selector.
If we want control every /anchor/ to give style to every link in the page. We remain the selector by itself.

#+begin_example css
a {
    text-decoration: overline;
    color: green;
}
#+end_example

In this case, every anchor <a> tags in page will have overline with green color.

** Css control spesific tags.
If we want control the sepcific tags, we can use /style/ or use class. to generate class in Css, we add "." before name of class.
the name we make it by our self no sepcific names for classes.

#+begin_example css
.color_links{
    text-decoration: overline;
    color:green;
}
#+end_example

Inside the tags, we add attribute /class/ such below:

#+begin_example html
<a class="color_links">the link</a>
#+end_example

*** Note:
You can use more then one class in the same tags:
#+begin_example html
<a class="color_links_one color_links_two">the link</a>
#+end_example

** Css ID.
The CSS ID selector matches an element based on the value of the element's id attribute. In order for the element to be selected, its /id/ attribute must match exactly the value given in the selector.

#+begin_example css
/* The element with id="demo" */
#identified {
  background-color: skyblue;
}
#+end_example

Inside the tags, we add attribute /id/ such below

#+begin_example html
<div id="identified">This div has a special ID on it!</div>
<div>This is just a regular div.</div>
#+end_example

*** Important Note:
In the CSS, a class selector is a name preceded by a full stop (“.”) and an ID selector is a name preceded by a hash character (“#”). The difference between an ID and a class is that an ID can be used to identify one element, whereas a class can be used to identify more than one.

** Control all elements in page.
The ("*") selector selects all elements.The ("*") selector can also select all elements inside another element
#+begin_example css
  *{
  background-color: yellow;
}
#+end_example
