#+TITLE: Framing and Padding in HTML
#+Author: Mohammed K Alnahdi
#+Email: mohammed.alnahdi1991@gmail.com
#+Date: <2022-03-13 Sun>

* Introduction
As we know, all tags have behavior in disply (inline or block). Every element have also border, padding, and margin.

* Usage
To editing border, padding and margin you must add probities. The following example of usage.

** Padding
/padding/ is used to create space around an element's content, inside of any defined borders.

#+begin_example css
.editing_padding{
    padding: 50px;
    }
#+end_example

padding have probities like:

    - padding-top
    - padding-right
    - padding-bottom
    - padding-left
*** Note:
    - You can used percentage instead of px.
    - You can used padding by probities by one line.

      |-----------------------------------|
      | padding: top  right  bottom  left |
      |-----------------------------------|

      for example
      #+begin_example css
      .editing_padding{
        padding: 25px 50px 20px 30px;
        }
       #+end_example

It is same of:
        #+begin_example css
        .editing_padding{
            padding-top: 25px;
            padding-right: 50px;
            padding-bottom: 20px;
            padding-left:30px;
            }
        #+end_example
** Border.
/border/ The CSS border properties allow you to specify the style, width, and color of an element's border.

in /border/ there more ways:

*** using style of border.
We can use ways of style like below:

#+begin_example css
.border_style{
    border-style: dotted;
    }
#+end_example

most probities of styles:

    - dotted: Defines a dotted border
    - dashed: Defines a dashed border
    - solid: Defines a solid border
    - double: Defines a double border
    - groove: Defines a 3D grooved border. The effect depends on the border-color value
    - ridge: Defines a 3D ridged border. The effect depends on the border-color value
    - inset: Defines a 3D inset border. The effect depends on the border-color value
    - outset: Defines a 3D outset border. The effect depends on the border-color value
    - none: Defines no border
    - hidden: Defines a hidden border
*** using width of border
The /border-width/ property specifies the width of the four borders. The width can be set as a specific size (in px, pt, cm, em, etc) or by using one of the three pre-defined values: thin, medium, or thick:
#+begin_example css
p.three {
  border-style: solid;
  border-width: 25px 10px 4px 35px; /* 25px top, 10px right, 4px bottom and 35px left */
}
#+end_example

*** using border color
The /border-color/ property is used to set the color of the four borders.
#+begin_example css
p.one {
  border-style: solid;
  border-color: red;
}
#+end_example

You can use property specifies the width of the four border.
#+begin_example css
p.one {
  border-style: solid;
  border-color: red green blue yellow; /* red top, green right, blue bottom and yellow left */
}
#+end_example

** Margin
/margin/ properties are used to create space around elements, outside of any defined borders. With CSS, you have full control over the margins. There are properties for setting the margin for each side of an element (top, right, bottom, and left).

#+begin_example css
.editing_margin{
    margin: 50px;
    }
#+end_example

CSS has properties for specifying the margin for each side of an element:

    - margin-top
    - margin-right
    - margin-bottom
    - margin-left
and it same of padding to collapse the code to one line.
